# Generated by Django 4.2.7 on 2023-12-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('', 'Selecciona una opcion'), ('platos_destacados', 'Platos destacados'), ('nuestros_servicios', 'Nuestros servicios'), ('clientes_felices', 'Clientes felices')], default='', max_length=50)),
                ('small_title', models.CharField(blank=True, max_length=15, null=True, verbose_name='Titulo pequeño')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo principal')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('custom_cta_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='[OPCIONAL] call to action 1')),
                ('custom_cta_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='[OPCIONAL] call to action 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Contenido de bloques',
                'verbose_name_plural': 'Contenidos de bloques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user_review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario de clientes', 'verbose_name_plural': 'Comentarios de clientes'},
        ),
        migrations.RemoveField(
            model_name='user_review',
            name='section',
        ),
        migrations.AlterField(
            model_name='user_review',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='Comentarios del usuario'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review',
            field=models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_reviews', verbose_name='Imagen del usuario'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del usuario'),
        ),
        migrations.DeleteModel(
            name='review_section',
        ),
    ]
