# Generated by Django 4.2.7 on 2024-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sections_alter_user_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hero_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_banner_image', models.ImageField(upload_to='hero_banner', verbose_name='Imagen principal del carrusel del home')),
                ('hero_banner_image_alt', models.CharField(max_length=255, verbose_name='Descripcion ALT de la imagen')),
                ('hero_banner_title', models.CharField(max_length=25, verbose_name='Titulo del banner principal')),
                ('hero_banner_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del banner principal')),
                ('hero_banner_cta', models.CharField(max_length=255, verbose_name='Link del CTA del banner principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Bloque de carrusel',
                'verbose_name_plural': 'Contenido de carruseles',
                'ordering': ['-created_at'],
            },
        ),
    ]
