# Generated by Django 4.2.7 on 2024-01-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hero_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('dish_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=25, verbose_name='Nombre del plato')),
                ('dish_category', models.CharField(choices=[('', 'Selecciona una opcion'), ('especiales', 'Platos especiales'), ('corrientazos', 'Platos corrientazos'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], default='', max_length=50, verbose_name='Categoria del plato')),
                ('dish_description', models.TextField(verbose_name='Descripcion del plato')),
                ('dish_regular_price', models.IntegerField(verbose_name='Precio regular del plato')),
                ('dish_discounted_price', models.IntegerField(verbose_name='Precio oferta del plato')),
                ('dish_special', models.BooleanField(verbose_name='Es un plato especial?')),
                ('dish_image_preview', models.ImageField(upload_to='dishes_preview', verbose_name='Imagen vista superior')),
                ('dish_image_complete', models.ImageField(upload_to='dishes_complete', verbose_name='Imagen vista frontal')),
                ('dish_side_1', models.CharField(max_length=25, verbose_name='Acompañante 1')),
                ('dish_side_2', models.CharField(max_length=25, verbose_name='Acompañante 2')),
                ('dish_side_3', models.CharField(blank=True, max_length=25, null=True, verbose_name='Acompañante 3')),
                ('dish_side_4', models.CharField(blank=True, max_length=25, null=True, verbose_name='Acompañante 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos del menu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hero_banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Elemento del swiper del hero banner', 'verbose_name_plural': 'Contenido del main banner swiper'},
        ),
    ]
