# Generated by Django 4.2.7 on 2024-03-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dishes_alter_hero_banner_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dishes',
        ),
    ]
