# Generated by Django 4.2.7 on 2024-03-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_banner',
            name='hero_banner_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción del banner principal'),
        ),
        migrations.AlterField(
            model_name='hero_banner',
            name='hero_banner_title',
            field=models.CharField(max_length=100, verbose_name='Titulo del banner principal'),
        ),
    ]
