# Generated by Django 4.2.7 on 2024-03-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Categoria')),
                ('slug', models.SlugField(default='', help_text='La URL se completa de manera automatica, por favor modificalo solamente si deseas que este post de tu blog tenga una URL distinta a la creada', unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='dish_image_complete',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_slug',
            field=models.SlugField(default='no-url', help_text='La URL se completa de manera automatica, por favor modificalo solamente si deseas que este plato tenga una URL distinta a la creada', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del plato'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoria del plato'),
        ),
    ]
