# Generated by Django 4.2.7 on 2024-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_dishes_dish_image_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_description',
            field=models.TextField(verbose_name='Descripcion del plato (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_discounted_price',
            field=models.IntegerField(blank=True, help_text='Agregue valor solamente si el plato se encuentra en oferta.', verbose_name='Precio oferta del plato'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_image_preview',
            field=models.ImageField(upload_to='dishes_preview', verbose_name='Imagen vista superior (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del plato (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_regular_price',
            field=models.IntegerField(verbose_name='Precio regular del plato (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_side_1',
            field=models.CharField(max_length=25, verbose_name='Acompañante 1 (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_side_2',
            field=models.CharField(max_length=25, verbose_name='Acompañante 2 (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_slug',
            field=models.SlugField(default='', help_text='La URL se completa de manera automatica, por favor modificalo solamente si deseas que este plato tenga una URL distinta a la creada', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_special',
            field=models.BooleanField(help_text='Marque la casilla si desea que este plato aparezca en el carrusel de inicio del sitio web', verbose_name='Es un plato especial?'),
        ),
    ]
