# Generated by Django 5.0.3 on 2024-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_dishes_dish_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_coupon_code', models.CharField(help_text='En este campo tienes que agregar el codigo que quieres que represente un cupon de descuento', max_length=15, verbose_name='Codigo de descuento (Obligatorio)')),
                ('discount_coupon_enablement', models.BooleanField(help_text='Marque la casilla si desea habilitar este codigo de descuento', verbose_name='El cupon de descuento esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Cupon de descuento',
                'verbose_name_plural': 'Cupones de descuento',
                'ordering': ['-created_at'],
            },
        ),
    ]
