# Generated by Django 5.0.3 on 2024-05-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_coupon',
            name='discount_unit',
            field=models.CharField(choices=[('', 'Selecciona una opcion'), ('pesos_colombianos', 'Pesos'), ('porcentaje', 'Porcentaje'), ('envio_gratuito', 'Envio gratis')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='discount_coupon',
            name='discout_maximum',
            field=models.IntegerField(default=0, help_text='Ajuste este como valor maximo que podra descontar del cupon, no valido para envio gratuito', verbose_name='Maximo valor posible a descontar'),
        ),
        migrations.AddField(
            model_name='discount_coupon',
            name='discout_value',
            field=models.IntegerField(default=0, help_text='Agregue el valor que desea descontar, tenga en cuenta que si elije la opcion de envio gratis como unidad, se aplicara descuento al 100 por ciento del valor del envio', verbose_name='Valor de descuento del cupon'),
        ),
    ]
