# Generated by Django 4.2.7 on 2024-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='Insertar texto de default', max_length=250, verbose_name='Descripcion corta'),
            preserve_default=False,
        ),
    ]
